CREATE TABLE IF NOT EXISTS "interviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"client_name" text NOT NULL,
	"unique_customer_identifier" text NOT NULL,
	"use_case" text NOT NULL,
	"interviewee_first_name" text NOT NULL,
	"interviewee_last_name" text NOT NULL,
	"interviewee_email" text NOT NULL,
	"interviewee_number" text,
	"call_id" text NOT NULL,
	"date_completed" timestamp NOT NULL,
	"interview_start_time" timestamp NOT NULL,
	"interview_end_time" timestamp NOT NULL,
	"total_interview_minutes" integer NOT NULL,
	"conversation_history_raw" text,
	"conversation_history_cleaned" text,
	"interview_audio_link" text,
	"client_company_description" text,
	"agent_name" text NOT NULL,
	"voice_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
